### ISSUE TITLE
Move Tooltips to Storybook/Catalog

### ISSUE THREAD

**Issue by borabiricik** [BursaBT/bbt-cms-web#11]
#### Description: We'll need to create a storybook catalog for tooltip components. 
Task: 
1- Move all tooltips under "src/pages/components/tooltips/index.tsx" to storybook. 
2- After being sure all tooltips are moved, be sure all folders and directories related, has been deleted.

Conclusion: After moving tooltips under storybook, we won't need any extra page to show tooltips. Developers will be able to inspect them from storybook.
---------------------------------------------------------------------------------------------------------------------------------
#### Tanım: Tüm tooltip ve varyantları için storybook kataloğunun oluşturulması.
Görev:
1- "src/pages/components/tooltips/index.tsx" dosyası içerisindeki tüm tooltiplerin storybook kataloğu altına alınması.
2- Taşıma işleminin bittiğinden emin olduktan sonra alakalı olan dosya ve klasörlerin silinmesi.

Sonuç: Tüm tooltiplerı storybook altına taşıdıktan sonra geliştiriciler ekstra bir sayfaya ihtiyaç duymadan storybook içerisinden ilgili componenti inceleyebilecek.

**Comment by Demir-Utku** [comment]
I can get this task.
