### ISSUE TITLE
Move Avatars to Storybook/Catalog

### ISSUE THREAD

**Issue by borabiricik** [BursaBT/bbt-cms-web#12]
#### Description: We'll need to create a storybook catalog for avatar components. 
Task: 
1- Move all avatars under "src/pages/components/avatars/index.tsx" to storybook. 
2- After being sure all avatars are moved, be sure all folders and directories related, has been deleted.

Conclusion: After moving avatars under storybook, we won't need any extra page to show avatars. Developers will be able to inspect them from storybook.
---------------------------------------------------------------------------------------------------------------------------------
#### Tanım: Tüm avatar ve varyantları için storybook kataloğunun oluşturulması.
Görev:
1- "src/pages/components/avatars/index.tsx" dosyası içerisindeki tüm avatarlarin storybook kataloğu altına alınması.
2- Taşıma işleminin bittiğinden emin olduktan sonra alakalı olan dosya ve klasörlerin silinmesi.

Sonuç: Tüm avatarların storybook altına taşıdıktan sonra geliştiriciler ekstra bir sayfaya ihtiyaç duymadan storybook içerisinden ilgili componenti inceleyebilecek.

**Comment by Demir-Utku** [comment]
I can get this task.
