### ISSUE TITLE
Move Modals to Storybook/Catalogs

### ISSUE THREAD

**Issue by borabiricik** [BursaBT/bbt-cms-web#8]
#### Description: We'll need to create a storybook catalog for modal components. 
Task: 
1- Move all modals under "src/pages/components/modals/index.tsx" to storybook. 
2- After being sure all modals are moved, be sure all folders and directories related, has been deleted.

Conclusion: After moving buttons under storybook, we won't need any extra page to show modals. Developers will be able to inspect them from storybook.
---------------------------------------------------------------------------------------------------------------------------------
#### Tanım: Tüm modal ve varyantları için storybook kataloğunun oluşturulması.
Görev:
1- "src/pages/components/modals/index.tsx" dosyası içerisindeki tüm modallari storybook kataloğu altına alınması.
2- Taşıma işleminin bittiğinden emin olduktan sonra alakalı olan dosya ve klasörlerin silinmesi.

Sonuç: Tüm modallari storybook altına taşıdıktan sonra geliştiriciler ekstra bir sayfaya ihtiyaç duymadan storybook içerisinden ilgili componenti inceleyebilecek.

**Comment by YagmurrrCan** [comment]
I can.
